ReserveSport/Areas/Admin/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Interface;
using Application.ViewModel.Ticket;

using ReserveSport.Helper;
using ClaimsPrincipalExtensions = ReserveSport.Other.ClaimsPrincipalExtensions;

namespace ReserveSport.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Access(1)]
    public class TicketController : Controller
    {
        private readonly ITicketService _ticket;

        public TicketController(ITicketService ticket)
        {
            _ticket = ticket;
        }
        [HttpGet]
        [Route("/Admin/Ticket/{search?}")]
        public IActionResult Index(string search="",int page=1)
        {
            var model = _ticket.GetAllTickets(search??"", page);
            ViewBag.Search = search;
            return View(model);
        }

        [HttpGet]
        [Route("/Admin/Ticket/Show/{id}")]
        public IActionResult Show(int id ,bool close)
        {
            ViewBag.Id = id;
            ViewBag.Close = close;
            ViewBag.User = UserName();
            var model = _ticket.GetSubTicket(id).Result;
            return View(model);
        }
        [HttpGet]
        [Route("/Admin/Ticket/Answer/{id}")]
        public IActionResult AnswerTicket(int id)
        {
            ViewBag.Id = id;
            ViewBag.UserId = Convert.ToInt32(ClaimsPrincipalExtensions.GetUserId(User));
            return View();
        }
        [HttpPost]
        [Route("/Admin/Ticket/Answer/{id}")]
        public IActionResult AnswerTicket(SubTicketViewModel model)
        {
            if (ModelState.IsValid)
            {
                _ticket.CreateSub(model);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.Id = model.TicketId;
                ViewBag.UserId = model.UserId;
                return View(model);
            }
        }
        [HttpGet]
        [Route("/Admin/Ticket/FileTicket/{id}")]
        public IActionResult FileTicket(int id)
        {
            var model = _ticket.GetFiles(id).Result;
            return View(model);
        }

        [HttpGet]
        [Route("/Admin/Ticket/Close/{id}")]
        public void Close(int id)
        {
            _ticket.Close(id);
        }
        public string UserName()
        {
            return ClaimsPrincipalExtensions.GetUserName(User);
        }
    }
}

ReserveSport/Areas/Customer/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Interface;
using Application.ViewModel.Ticket;
using Microsoft.AspNetCore.Authorization;
using ReserveSport.Helper;
using ClaimsPrincipalExtensions = ReserveSport.Other.ClaimsPrincipalExtensions;

namespace ReserveSport.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class TicketController : Controller
    {
        private readonly ITicketService _ticket;

        public TicketController(ITicketService ticket)
        {
            _ticket = ticket;
        }
        [HttpGet]
        [Route("/Profile/Ticket")]
        public IActionResult Ticket()
        {
            var model = _ticket.GetTickets(UserId()).Result;
            return View(model);
        }

        [HttpGet]
        [Route("/Profile/AddTicket")]
        public IActionResult AddTicket()
        {
            ViewBag.Id = UserId();
            return View();
        }
        [HttpPost]
        [Route("/Profile/AddTicket")]
        public IActionResult AddTicket(TicketViewModel model)
        {
            if (ModelState.IsValid)
            {
                _ticket.Create(model);
                return RedirectToAction(nameof(Ticket));
            }
            else
            {
                ViewBag.Id =model.UserId;
                return View(model);
            }
           
        }

        [HttpGet]
        [Route("/Profile/Tickets/{id}")]
        public IActionResult Tickets(int id,bool close)
        {
            ViewBag.close = close;
            var model = _ticket.GetSubTicket(id).Result;
            ViewBag.Name = ClaimsPrincipalExtensions.GetUserName(User);
            ViewBag.Id = id;
            return View(model);
        }

        [HttpGet]
        [Route("/Profile/Answer/{id}")]
        public IActionResult Answer(int id)
        {
            ViewBag.Id = id;
            ViewBag.UserId = UserId();
            return View();
        }

        [HttpPost]
        [Route("/Profile/Answer/{id}")]
        public IActionResult Answer(SubTicketViewModel model)
        {
            if (ModelState.IsValid)
            {
                _ticket.CreateSub(model);
                return RedirectToAction(nameof(Ticket));
            }
            else
            {
                ViewBag.Id = model.TicketId;
                ViewBag.UserId = UserId();
                return View(model);
            }
        }

        [HttpGet]
        [Route("/Profile/File/{id}")]
        public IActionResult File(int id)
        {
            var model = _ticket.GetFiles(id).Result;
            return View(model);
        }
        public int UserId()
        {
            int user = Convert.ToInt32(ClaimsPrincipalExtensions.GetUserId(User));
            return user;
        }
    }
}

ReserveSport/Areas/Admin/Views/Ticket/AnswerTicket.cshtml
@model SubTicketViewModel
@{
    ViewData["Title"] = "پاسخ تیکت";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row mt-4">
        <div class="card col-12">
            <form asp-controller="Ticket" asp-action="AnswerTicket" enctype="multipart/form-data">
                <div class="card-body">
                    <h4 class="card-title font text-success">پاسخ تیکت</h4>
                    <hr /><input type="hidden" asp-for="UserId" value="@ViewBag.UserId" />
                    <input type="hidden" asp-for="TicketId" value="@ViewBag.Id" />
                    <div class="form-group mb-0 row">
                        <div class="col-lg-3">
                            <label class="col-form-label font">متن</label>
                        </div>
                        <div class="col-lg-8">
                            <textarea id="maxlength-textarea" asp-for="SubText" class="form-control" maxlength="900" rows="8" placeholder="حداکثر 900 کاراکتر مجاز است"></textarea>
                            <span class="font text-danger" asp-validation-for="SubText"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-lg-3">
                            <label class="col-form-label font">فایل</label>
                        </div>
                        <div class="col-lg-8 mt-4">
                            <input asp-for="File" type="file">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-sm btn-success text-white">ارسال</button>
                </div>

            </form>
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Ticket/FileTicket.cshtml
@model List<FileTicketViewModel>
@{
    ViewData["Title"] = "پیوست ها";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row mt-4">

    <div class="card">
        <div class="row p-2">
            @foreach (var item in Model)
            {

                <div class="col-3">
                    <img src="~/Images/@item.File" class="img-fluid img-thumbnail mx-2" style="width: 100%" height="80" />
                </div>

            }
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Ticket/Index.cshtml
@model Tuple<List<TicketItemViewModel>, int, int>
@{
    ViewData["Title"] = "تیکت ها";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h6 class="card-title">لیست تیکت ها </h6>
                <div class="row justify-content-between">

                    <form class="col-md-4 position-relative" asp-controller="Ticket" asp-action="Index" method="get">



                        <input name="search" class="form-control mr-auto" placeholder="جستجو  تیکت ها..." style="padding-left: 65px">
                        <button type="submit" class="btn btn-primary ml-2 position-absolute" style="left: 5px; top: 0; height: 100%; border-radius: 2px;">
                            ثبت
                        </button>


                    </form>

                </div>
                <div class="table-responsive pt-3">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    نام کاربر
                                </th>

                                <th>
                                    عنوان تیکت
                                </th>
                                <th>
                                    وضعیت
                                </th>

                                <th>تاریخ</th>
                                <th>
                                    عملیات
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Item1)
                            {
                            <tr id="item_@item.TicketId">

                                <td>
                                    @item.User
                                </td>
                                <td>
                                    @item.TicketTitle
                                </td>
                                @if (item.Close)
                                {
                                    <td>
                                        <span class="badge badge-danger text-white">بسته شد</span>
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        <span class="badge badge-success text-white">باز است</span>
                                    </td>
                                }
                                <td>@item.TicketDate</td>

                                <td>
                                    <div class="dropdown mb-2">
                <button class="btn p-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal icon-lg text-muted pb-3px"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item d-flex align-items-center" asp-controller="Ticket" asp-action="Show" asp-route-id="@item.TicketId" asp-route-close="@item.Close">
                        <span class="">پیام</span>
                    </a>

                 @if (item.Close == false)
                 {
                     <button onclick="Close('@item.TicketId')" class="dropdown-item d-flex align-items-center">
                         <span class="">بستن تیکت</span>
                     </button>
                 }

                </div>

            </div>
                            </td>
                            </tr>
                                }
                        </tbody>
                    </table>
                    @if (Model.Item2 > 1)
                    {
                        <div class="dataTables_paginate paging_simple_numbers py-3 d-flex justify-content-center" id="dataTableExample_paginate">
                            <ul class="pagination">
                                <li class="paginate_button page-item previous @((Model.Item3-1 == 0) ? "disabled" : "")" id="dataTableExample_previous">
                                    <a href="/Admin/Ticket?page=@(Model.Item3-1)&search=@ViewBag.Search" aria-controls="dataTableExample" data-dt-idx="0" tabindex="0" class="page-link">قبلی</a>
                                </li>
                                @for (int i = 1; i <= (Model.Item2); i++)
                                {
                                    <li class="paginate_button page-item @(Model.Item3==i?"active":"")">
                                        <a href="/Admin/Ticket?page=@i&search=@ViewBag.Search" aria-controls="dataTableExample" data-dt-idx="1" tabindex="0" class="page-link">@i</a>
                                    </li>
                                }
                                <li class="paginate_button page-item @((Model.Item3+1 > Model.Item2) ? "disabled" : "")" id="dataTableExample_next">
                                    <a href="/Admin/Ticket?page=@(Model.Item3+1)&search=@ViewBag.Search" aria-controls="dataTableExample" data-dt-idx="4" tabindex="0" class="page-link">بعدی</a>
                                </li>
                            </ul>
                        </div>
                    }
                </div>
             
            </div>
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Ticket/Show.cshtml
@model List<ItemSubTicketViewModel>
@{
    ViewData["Title"] = "پیام ها";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="container">
    <div class="row mt-4">
     
        <div class="card col-12">
            <div class="row">
                @if (ViewBag.Close)
                {
                    <a  class="btn col-3 mr-2  font mt-3 btn-sm btn-primary text-white"> تیکت بسته شده</a>

                }
                else
                {
                    <a asp-controller="Ticket" asp-action="AnswerTicket" asp-route-id="@ViewBag.Id" class="btn col-3 mr-2  font mt-3 btn-sm btn-primary text-white">پاسخ</a>

                }
                <a asp-controller="Ticket" asp-action="FileTicket" asp-route-id="@ViewBag.Id" class="btn col-3 font mr-2 mt-3 btn-sm btn-warning text-white">پیوست ها</a>

            </div>     <hr />
            @foreach (var item in Model)
            {
                @if (item.UserName == ViewBag.Name)
                {
                    <div class="alert alert-success font">

                        <small class="font">@item.UserName</small>
                        <hr />
                        @item.SubText
                        <hr />
                        <small class="font">تاریخ:@item.Time</small>
                    </div>
                }
                else
                {
                    <div class="alert alert-warning font">
                        <small class="font">@item.UserName</small>
                        <hr />
                        @item.SubText
                        <hr />
                        <small class="font">تاریخ:@item.Time</small>
                    </div>
                }
            }
           
        </div>
    </div>
</div>