ReserveSport/Areas/Admin/Controllers/SportController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Interface;
using Application.ViewModel.Sport;
using ReserveSport.Helper;

namespace ReserveSport.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Access(1)]
    public class SportController : Controller
    {
        private readonly ISportService _sport;

        public SportController(ISportService sport)
        {
            _sport = sport;
        }
        [HttpGet]
        [Route("/Admin/Sport/{search?}")]
        public IActionResult Index(string search="",int page=1)
        {
            var model = _sport.GetSports(search ?? "", page);
            ViewBag.search = search;
            return View(model);
        }

        [HttpGet]
        [Route("/Admin/Sport/Create")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Route("/Admin/Sport/Create")]
        public IActionResult Create(CreateSportViewModel model)
        {
            if (ModelState.IsValid)
            {
                _sport.Add(model);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
           
        }

        [HttpGet]
        [Route("/Admin/Sport/Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var model = _sport.GetSportById(id).Result;
            return View(model);
        }

        [HttpPost]
        [Route("/Admin/Sport/Edit/{id}")]
        public IActionResult Edit(EditSportViewModel model)
        {
            if (ModelState.IsValid)
            {
                _sport.Edit(model);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        [Route("/Admin/Sport/Remove/{id}")]
        public void Remove(int id)
        {
            _sport.Remove(id);
        }

        [HttpGet]
        [Route("/Admin/Sport/trash/{search?}")]
        public IActionResult TrashSport(string search = "", int page = 1)
        {
            var model = _sport.GetTrashSports(search ?? "", page);
            ViewBag.search = search;
            return View(model);
        }

        [HttpGet]
        [Route("/Admin/Sport/Back/{id}")]
        public void Back(int id)
        {
            _sport.Back(id);
        }
        [HttpGet]
        [Route("/Admin/Sport/Delete/{id}")]
        public void Delete(int id)
        {
            _sport.Delete(id);
        }
    }
}

ReserveSport/Areas/Admin/Views/Sport/Create.cshtml
@model CreateSportViewModel
@{
    ViewData["Title"] = "افزودن رشته ورزشی";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div class="row">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <div class="d-flex justify-content-end px-4">
                <a class="d-inline-block mt-3 text-black" href="/Admin/sport">
                   رشته های ورزشی
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left">
                        <line x1="19" y1="12" x2="5" y2="12"></line>
                        <polyline points="12 19 5 12 12 5"></polyline>
                    </svg>
                </a>
            </div>
            <div class="card-body pt-0">
                <h6 class="card-title">افزودن رشته ورزشی جدید</h6>
                <form asp-controller="Sport" asp-action="Create" method="post">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label class="control-label">نام رشته ورزشی</label>
                            <input type="text" asp-for="SportName" class="form-control" placeholder="نام استان را وارد کنید">
                        </div>
                        <span class="text-danger" asp-validation-for="SportName"></span>

                       
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">توضیحات رشته ورزشی</label>
                        <textarea class="form-control" asp-for="SportDescription" id="exampleFormControlTextarea1" rows="5"></textarea>
                        <span class="text-info">توضیحات به بهبود سئو سایت کمک میکند</span>
                        </div>
                    <button type="submit" class="btn btn-primary submit">ثبت</button>
                </form>
            </div>
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Sport/Edit.cshtml
@model EditSportViewModel
@{
    ViewData["Title"] = "ویرایش رشته ورزشی";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="row">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <div class="d-flex justify-content-end px-4">
                <a class="d-inline-block mt-3 text-black" href="/Admin/sport">
                    رشته های ورزشی
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left">
                        <line x1="19" y1="12" x2="5" y2="12"></line>
                        <polyline points="12 19 5 12 12 5"></polyline>
                    </svg>
                </a>
            </div>
            <div class="card-body pt-0">
                <h6 class="card-title">ویرایش رشته ورزشی </h6>
                <form asp-controller="Sport" asp-action="Edit" method="post">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label class="control-label">نام رشته ورزشی</label>
                            <input type="text" asp-for="SportName" class="form-control" placeholder="نام استان را وارد کنید">
                        </div>
                        <span class="text-danger" asp-validation-for="SportName"></span>

                       <input type="hidden" asp-for="SportId"/>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">توضیحات رشته ورزشی</label>
                        <textarea class="form-control" asp-for="SportDescription" id="exampleFormControlTextarea1" rows="5"></textarea>
                        <span class="text-info">توضیحات به بهبود سئو سایت کمک میکند</span>
                    </div>
                    <button type="submit" class="btn btn-primary submit">ثبت</button>
                </form>
            </div>
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Sport/Index.cshtml
@model Tuple<List<SportViewModel>, int, int>
@{
    ViewData["Title"] = "رشته های ورزشی";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h6 class="card-title">لیست ورزش ها</h6>
                <div class="row justify-content-between">
                    <div class="col-md-6 mb-1 mb-md-0">
                        <a href="/Admin/Sport/Create" class="btn text-white btn-success">افزودن</a>
                    </div>
                    <form class="col-md-4 position-relative" asp-controller="Sport" asp-action="Index" method="get">



                        <input name="search" class="form-control mr-auto" placeholder="جستجو رشته ها..." style="padding-left: 65px">
                        <button type="submit" class="btn btn-primary ml-2 position-absolute" style="left: 5px; top: 0; height: 100%; border-radius: 2px;">
                            ثبت
                        </button>


                    </form>

                </div>
                <div class="table-responsive pt-3">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    نام رشته ورزشی
                                </th>
                                
                                <th>
                                    عملیات
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Item1)
                            {
                                <tr id="item_@item.SportId">
                                    <td>
                                        @item.SportName
                                    </td>
                                    

                                    <td>
                                        <div class="dropdown mb-2">
                                            <button class="btn p-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal icon-lg text-muted pb-3px"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
                                            </button>
                                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                                <a class="dropdown-item d-flex align-items-center" href="/Admin/Sport/Edit/@item.SportId"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2 icon-sm ml-2"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg> <span class="">ویرایش</span></a>
                                                <button onclick="DeleteSport('@item.SportId')" class="dropdown-item d-flex align-items-center"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash icon-sm ml-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg> <span class="">حذف</span></button>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @if (Model.Item2 > 1)
                    {
                        <div class="dataTables_paginate paging_simple_numbers py-3 d-flex justify-content-center" id="dataTableExample_paginate">
                            <ul class="pagination">
                                <li class="paginate_button page-item previous @((Model.Item3-1 == 0) ? "disabled" : "")" id="dataTableExample_previous">
                                    <a href="/Admin/Sport?page=@(Model.Item3-1)&search=@ViewBag.Search" aria-controls="dataTableExample" data-dt-idx="0" tabindex="0" class="page-link">قبلی</a>
                                </li>
                                @for (int i = 1; i <= (Model.Item2); i++)
                                {
                                    <li class="paginate_button page-item @(Model.Item3==i?"active":"")">
                                        <a href="/Admin/Sport?page=@i&search=@ViewBag.Search" aria-controls="dataTableExample" data-dt-idx="1" tabindex="0" class="page-link">@i</a>
                                    </li>
                                }
                                <li class="paginate_button page-item @((Model.Item3+1 > Model.Item2) ? "disabled" : "")" id="dataTableExample_next">
                                    <a href="/Admin/Sport?page=@(Model.Item3+1)&search=@ViewBag.Search" aria-controls="dataTableExample" data-dt-idx="4" tabindex="0" class="page-link">بعدی</a>
                                </li>
                            </ul>
                        </div>
                    }
                </div>
                <a class="d-inline-block mt-4 text-black" href="/admin/Sport/Trash">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2">
                        <polyline points="3 6 5 6 21 6"></polyline>
                        <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                        <line x1="10" y1="11" x2="10" y2="17"></line>
                        <line x1="14" y1="11" x2="14" y2="17"></line>
                    </svg>
                    حذفیات
                </a>
            </div>
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Sport/TrashSport.cshtml
@model Tuple<List<SportViewModel>, int, int>
@{
    ViewData["Title"] = "بازیافت رشته های ورزشی";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h6 class="card-title">بازیافت ورزش ها</h6>
                <div class="row justify-content-between">
                   
                    <form class="col-md-4 position-relative" asp-controller="Sport" asp-action="TrashSport" method="get">



                        <input name="search" class="form-control mr-auto" placeholder="جستجو رشته ها..." style="padding-left: 65px">
                        <button type="submit" class="btn btn-primary ml-2 position-absolute" style="left: 5px; top: 0; height: 100%; border-radius: 2px;">
                            ثبت
                        </button>


                    </form>

                </div>
                <div class="table-responsive pt-3">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    نام رشته ورزشی
                                </th>

                                <th>
                                    عملیات
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Item1)
                            {
                                <tr id="item_@item.SportId">
                                    <td>
                                        @item.SportName
                                    </td>


                                    <td>
                                        <div class="dropdown mb-2">
                                            <button class="btn p-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal icon-lg text-muted pb-3px"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
                                            </button>
                                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">

                                                <button onclick="BackSport('@item.SportId')" class="dropdown-item d-flex align-items-center">
                                                    <span class="">بازگردانی</span>
                                                </button>
                                                <button onclick="RemoveSport('@item.SportId')" class="dropdown-item d-flex align-items-center">
                                                    <span class="">حذف</span>
                                                </button>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @if (Model.Item2 > 1)
                    {
                        <div class="dataTables_paginate paging_simple_numbers py-3 d-flex justify-content-center" id="dataTableExample_paginate">
                            <ul class="pagination">
                                <li class="paginate_button page-item previous @((Model.Item3-1 == 0) ? "disabled" : "")" id="dataTableExample_previous">
                                    <a href="/Admin/Sport/trash?page=@(Model.Item3-1)&search=@ViewBag.Search" aria-controls="dataTableExample" data-dt-idx="0" tabindex="0" class="page-link">قبلی</a>
                                </li>
                                @for (int i = 1; i <= (Model.Item2); i++)
                                {
                                    <li class="paginate_button page-item @(Model.Item3==i?"active":"")">
                                        <a href="/Admin/Sport/trash?page=@i&search=@ViewBag.Search" aria-controls="dataTableExample" data-dt-idx="1" tabindex="0" class="page-link">@i</a>
                                    </li>
                                }
                                <li class="paginate_button page-item @((Model.Item3+1 > Model.Item2) ? "disabled" : "")" id="dataTableExample_next">
                                    <a href="/Admin/Sport/trash?page=@(Model.Item3+1)&search=@ViewBag.Search" aria-controls="dataTableExample" data-dt-idx="4" tabindex="0" class="page-link">بعدی</a>
                                </li>
                            </ul>
                        </div>
                    }
                </div>
                <a class="d-inline-block mt-4 text-black" href="/admin/Sport">
                   
                   لیست اصلی
                </a>
            </div>
        </div>
    </div>
</div>