ReserveSport/Areas/Admin/Controllers/GeneralController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Interface;
using Application.ViewModel.General;
using Application.ViewModel.Setting;
using ReserveSport.Helper;

namespace ReserveSport.Areas.Admin.Controllers
{[Area("Admin")]
    [Access(1)]
    public class GeneralController : Controller
    {
        private readonly ISettingService _setting;

        public GeneralController(ISettingService setting)
        {
            _setting = setting;
        }
        [HttpGet][Route("/Admin/Setting")]
        public IActionResult Setting()
        {
            var model = _setting.GetSetting(1).Result;
            return View(model);
        }
        [HttpPost]
        [Route("/Admin/Setting")]
        public IActionResult Setting(SettingViewModel model)
        {
            _setting.Setting(model);
            return RedirectToAction(nameof(Setting));
        }
        [HttpGet]
        [Route("/Admin/Complaint/{search?}")]
        public IActionResult Complaint(string search = "", int page = 1)
        {
            ViewBag.search = search;
            var model = _setting.GetComplaints(search??"", page);
            return View(model);
        }

        [HttpGet]
        [Route("/Admin/About")]
        public IActionResult About()
        {
            var model = _setting.GetAbout().Result;
            return View(model);
        }
        [HttpPost]
        [Route("/Admin/About")]
        public IActionResult About(AboutViewModel model)
        {
            _setting.Insert(model);
            return RedirectToAction(nameof(About));
        }

        [HttpGet]
        [Route("/Admin/Contact/{search?}")]
        public IActionResult Contact(string search = "", int page = 1)
        {
            var model = _setting.GetContact(search??"", page);
            ViewBag.search = search;
            return View(model);
        }
    }
}

ReserveSport/Areas/Admin/Controllers/SmsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Interface;
using Application.ViewModel.Sms;
using ReserveSport.Helper;

namespace ReserveSport.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Access(1)]
    public class SmsController : Controller
    {
        private readonly ISmsService _sms;

        public SmsController(ISmsService sms)
        {
            _sms = sms;
        }
        [HttpGet][Route("/Admin/Sms/Collection")]
        public IActionResult Admin()
        {
            var model = _sms.GetSmsAdmin(1).Result;
            return View(model);
        }

        [HttpPost]
        [Route("/Admin/Sms/Collection")]
        public IActionResult Admin(SmsAdminViewModel model)
        {
            _sms.SmsAdmin(model);
            return RedirectToAction(nameof(Admin));
        }
        [HttpGet]
        [Route("/Admin/Sms/Customer")]
        public IActionResult Customer()
        {
            var model = _sms.GetSmsCustomer(1).Result;
            return View(model);
        }

        [HttpPost]
        [Route("/Admin/Sms/Customer")]
        public IActionResult Customer(SmsCustomerViewModel model)
        {
            _sms.SmsCustomer(model);
            return RedirectToAction(nameof(Customer));
        }
        [HttpGet]
        [Route("/Admin/Sms/General")]
        public IActionResult General()
        {
            var model = _sms.GetSmsGeneral(1).Result;
            return View(model);
        }

        [HttpPost]
        [Route("/Admin/Sms/General")]
        public IActionResult General(SmsGeneralViewModel model)
        {
            _sms.SmsGeneral(model);
            return RedirectToAction(nameof(General));
        }
        [HttpGet]
        [Route("/Admin/Sms/Thank")]
        public IActionResult Thank()
        {
            var model = _sms.GetSmsThank(1).Result;
            return View(model);
        }

        [HttpPost]
        [Route("/Admin/Sms/Thank")]
        public IActionResult Thank(SmsThankViewModel model)
        {
            _sms.SmsThank(model);
            return RedirectToAction(nameof(Thank));
        }
        [HttpGet]
        [Route("/Admin/Sms/Remember")]
        public IActionResult Remember()
        {
            var model = _sms.GetSmsRemember(1).Result;
            return View(model);
        }

        [HttpPost]
        [Route("/Admin/Sms/Remember")]
        public IActionResult Remember(SmsRememberViewModel model)
        {
            _sms.SmsRemember(model);
            return RedirectToAction(nameof(Remember));
        }
    }
}

ReserveSport/Areas/Customer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Interface;
using ReserveSport.Helper;
using ClaimsPrincipalExtensions = ReserveSport.Other.ClaimsPrincipalExtensions;
using Application.ViewModel.User;
using Microsoft.AspNetCore.Authorization;

namespace ReserveSport.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IUserService _user;
        private readonly IWalletServcie _wallet;
        private readonly IOrderService _order;

        public HomeController(IUserService user, IWalletServcie wallet, IOrderService order)
        {
            _user = user;
            _wallet = wallet;
            _order = order;
        }
        [HttpGet]
        [Route("/Profile")]
        public IActionResult Index()
        {
            ViewBag.Collection = _user.GetCollectionId(UserId()).Result;
            var model = _user.GetProfile(UserId()).Result;
            return View(model);
        }

        [HttpGet]
        [Route("/Profile/Wallet")]
        public IActionResult Wallet()
        {
            var model = _user.GetUserWallet(UserId()).Result;
            return View(model);
        }
        [HttpPost]
        [Route("/Profile/ChargeWallet")]
        public IActionResult ChargeWallet(UserWalletViewModel model)
        {
            if (model.Price == 0)
            {
                return Redirect("/Profile/Wallet");
            }
            _wallet.UpdateWallet(model);
            return Redirect($"/ChargeWallet/{model.Price}");
        }

        [HttpGet]
        [Route("/Profile/Orders")]
        public IActionResult Orders(int page = 1)
        {
            var model = _order.GetUserOrderList(UserId(), page);
            return View(model);
        }

        [HttpGet]
        [Route("/Profile/ShowOrder/{id}")]
        public IActionResult Show(int id)
        {
            var model = _order.GetItems(id).Result;
            return View(model);
        }
        public int UserId()
        {
            int user = Convert.ToInt32(ClaimsPrincipalExtensions.GetUserId(User));
            return user;
        }
    }
}

ReserveSport/Areas/Customer/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Interface;
using Application.ViewModel.Ticket;
using Microsoft.AspNetCore.Authorization;
using ReserveSport.Helper;
using ClaimsPrincipalExtensions = ReserveSport.Other.ClaimsPrincipalExtensions;

namespace ReserveSport.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class TicketController : Controller
    {
        private readonly ITicketService _ticket;

        public TicketController(ITicketService ticket)
        {
            _ticket = ticket;
        }
        [HttpGet]
        [Route("/Profile/Ticket")]
        public IActionResult Ticket()
        {
            var model = _ticket.GetTickets(UserId()).Result;
            return View(model);
        }

        [HttpGet]
        [Route("/Profile/AddTicket")]
        public IActionResult AddTicket()
        {
            ViewBag.Id = UserId();
            return View();
        }
        [HttpPost]
        [Route("/Profile/AddTicket")]
        public IActionResult AddTicket(TicketViewModel model)
        {
            if (ModelState.IsValid)
            {
                _ticket.Create(model);
                return RedirectToAction(nameof(Ticket));
            }
            else
            {
                ViewBag.Id =model.UserId;
                return View(model);
            }
           
        }

        [HttpGet]
        [Route("/Profile/Tickets/{id}")]
        public IActionResult Tickets(int id,bool close)
        {
            ViewBag.close = close;
            var model = _ticket.GetSubTicket(id).Result;
            ViewBag.Name = ClaimsPrincipalExtensions.GetUserName(User);
            ViewBag.Id = id;
            return View(model);
        }

        [HttpGet]
        [Route("/Profile/Answer/{id}")]
        public IActionResult Answer(int id)
        {
            ViewBag.Id = id;
            ViewBag.UserId = UserId();
            return View();
        }

        [HttpPost]
        [Route("/Profile/Answer/{id}")]
        public IActionResult Answer(SubTicketViewModel model)
        {
            if (ModelState.IsValid)
            {
                _ticket.CreateSub(model);
                return RedirectToAction(nameof(Ticket));
            }
            else
            {
                ViewBag.Id = model.TicketId;
                ViewBag.UserId = UserId();
                return View(model);
            }
        }

        [HttpGet]
        [Route("/Profile/File/{id}")]
        public IActionResult File(int id)
        {
            var model = _ticket.GetFiles(id).Result;
            return View(model);
        }
        public int UserId()
        {
            int user = Convert.ToInt32(ClaimsPrincipalExtensions.GetUserId(User));
            return user;
        }
    }
}

ReserveSport/Areas/Admin/Views/Sms/Admin.cshtml
@model SmsAdminViewModel
@{
    ViewData["Title"] = "تنظیمات پیامکی";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row ">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <div class="d-flex justify-content-end px-4">

            </div>
            <div class="card-body mx-5 pt-0">
                <h6 class="card-title mt-5">پیامک مدیر مجموعه</h6>

                <form asp-controller="Sms" asp-action="Admin" method="post">

                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن کاربر</label>
                            <input type="text" asp-for="NameText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>رشته ورزشی</label>
                            <input type="text" asp-for="SportText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن ساعت شروع</label>
                            <input type="text" asp-for="StartText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label> متن ساعت پایان</label>
                            <input type="text" asp-for="EndText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن روز </label>
                            <input type="text" asp-for="DayText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن هزینه</label>
                            <input type="text" asp-for="PriceText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن کد سانس</label>
                            <input type="text" asp-for="CodeText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن سایت</label>
                            <input type="text" asp-for="SiteText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>لینک سایت</label>
                            <input type="url" asp-for="SiteLink" class="form-control">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success submit">ذخیره</button>
                </form>
            </div>
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Sms/Customer.cshtml
@model SmsCustomerViewModel
@{
    ViewData["Title"] = "تنظیمات پیامکی";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div class="row ">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <div class="d-flex justify-content-end px-4">

            </div>
            <div class="card-body mx-5 pt-0">
                <h6 class="card-title mt-5">پیامک خریدار سانس</h6>

                <form asp-controller="Sms" asp-action="Customer" method="post">

                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن کاربر</label>
                            <input type="text" asp-for="NameText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>مجموعه ورزشی</label>
                            <input type="text" asp-for="CollectionText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن ساعت شروع</label>
                            <input type="text" asp-for="StartText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label> متن ساعت پایان</label>
                            <input type="text" asp-for="EndText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن روز </label>
                            <input type="text" asp-for="DayText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن هزینه</label>
                            <input type="text" asp-for="PriceText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن نشانی</label>
                            <input type="text" asp-for="AddressText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن سایت</label>
                            <input type="text" asp-for="SiteText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>لینک سایت</label>
                            <input type="url" asp-for="SiteLink" class="form-control">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success submit">ذخیره</button>
                </form>
            </div>
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Sms/General.cshtml
@model SmsGeneralViewModel
@{
    ViewData["Title"] = "تنظیمات پیامکی";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row ">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <div class="d-flex justify-content-end px-4">

            </div>
            <div class="card-body mx-5 pt-0">
                <h6 class="card-title mt-5">پیامک عمومی</h6>

                <form asp-controller="Sms" asp-action="General" method="post">

                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>فعالسازی مجموعه</label>
                            <input type="text" asp-for="ActiveCollection" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>کد فعالسازی</label>
                            <input type="text" asp-for="ActiveText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>ثبت تیکت</label>
                            <input type="text" asp-for="AnswerText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>گذر واژه موقت</label>
                            <input type="text" asp-for="TemporaryText" class="form-control">
                        </div>
                    </div>
                   
                    <button type="submit" class="btn btn-success submit">ذخیره</button>
                </form>
            </div>
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Sms/Remember.cshtml
@model SmsRememberViewModel
@{
    ViewData["Title"] = "تنظیمات پیامکی";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row ">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <div class="d-flex justify-content-end px-4">

            </div>
            <div class="card-body mx-5 pt-0">
                <h6 class="card-title mt-5">پیامک یادآوری</h6>

                <form asp-controller="Sms" asp-action="Remember" method="post">

                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن کاربر</label>
                            <input type="text" asp-for="NameText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن مجموعه</label>
                            <input type="text" asp-for="CollectionText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن ساعت شروع</label>
                            <input type="text" asp-for="StartText" class="form-control">
                        </div>
                    </div>
                    
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن روز </label>
                            <input type="text" asp-for="DayText" class="form-control">
                        </div>
                    </div>
                    
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن توضیحات</label>
                            <input type="text" asp-for="Description" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن سایت</label>
                            <input type="text" asp-for="SiteText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>لینک سایت</label>
                            <input type="url" asp-for="SiteLink" class="form-control">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success submit">ذخیره</button>
                </form>
            </div>
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Sms/Thank.cshtml
@model SmsThankViewModel
@{
    ViewData["Title"] = "تنظیمات پیامکی";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row ">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <div class="d-flex justify-content-end px-4">

            </div>
            <div class="card-body mx-5 pt-0">
                <h6 class="card-title mt-5">پیامک تشکر</h6>

                <form asp-controller="Sms" asp-action="Thank" method="post">

                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن کاربر</label>
                            <input type="text" asp-for="NameText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>متن تشکر</label>
                            <input type="text" asp-for="ThankText" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label> متن توضیح</label>
                            <input type="text" asp-for="DescriptionText" class="form-control">
                        </div>
                    </div>
                    
                    <div class="col-sm-12">
                        <div class="form-group col-md-6">
                            <label>لینک سایت</label>
                            <input type="url" asp-for="SiteLink" class="form-control">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success submit">ذخیره</button>
                </form>
            </div>
        </div>
    </div>
</div>