ReserveSport/Areas/Admin/Controllers/ReserveController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Interface;
using Application.ViewModel.Reserve;
using ReserveSport.Helper;

namespace ReserveSport.Areas.Admin.Controllers
{[Area("Admin")]
    [Access(1)]
    public class ReserveController : Controller
    {
        private readonly IReserveService _reserve;

        public ReserveController(IReserveService reserve)
        {
            _reserve = reserve;
        }
        [HttpGet]
        [Route("/Admin/Reserve/{id}")]
        public IActionResult Index(int id,int page=1)
        {
            ViewBag.id = id;
            var model = _reserve.GetReserve(id, page);
            return View(model);
        }

        [HttpGet]
        [Route("/Admin/Reserve/Create/{id}")]
        public IActionResult Create(int id)
        {
            ViewBag.id = id;
            return View();
        }

        [HttpPost]
        [Route("/Admin/Reserve/Create/{id}")]
        public IActionResult Create(CreateReserveViewModel model)
        {
            if (ModelState.IsValid)
            {
                _reserve.Create(model);
                return Redirect($"/Admin/Reserve/{@model.CollectionId}");
            }
            else
            {
                ViewBag.id = model.CollectionId;
                return View();
            }
        }

        [HttpGet]
        [Route("/Admin/Reserve/Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var model = _reserve.GetReserveById(id).Result;
            return View(model);
        }
        [HttpPost]
        [Route("/Admin/Reserve/Edit/{id}")]
        public IActionResult Edit(EditReserveViewModel model)
        {
            if (ModelState.IsValid)
            {
                var check = _reserve.Exist(model.DayTime, model.StartTime, model.EndTime, model.Price).Result;
                if (check)
                {
                    ViewBag.Error = "سانسی با این مشخصات وجود دارد";
                    return View(model);
                }
                _reserve.Edit(model);
                return Redirect($"/Admin/Reserve/{@model.CollectionId}");

            }
            else
            {
                return View(model);
            }
          
        }

        [HttpGet]
        [Route("/Admin/Reserve/Delete/{id}")]
        public void Delete(int id)
        {
            _reserve.Delete(id);
        }
    }
}

ReserveSport/Areas/Admin/Views/Reserve/Create.cshtml
@model CreateReserveViewModel
@{
    ViewData["Title"] = "افزودن سانس";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <div class="d-flex justify-content-end px-4">
                <a class="d-inline-block mt-3 text-black" href="/Admin/Reserve/@ViewBag.id">
                    سانس ها
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left">
                        <line x1="19" y1="12" x2="5" y2="12"></line>
                        <polyline points="12 19 5 12 12 5"></polyline>
                    </svg>
                </a>
            </div>
            <div class="card-body pt-0">
                <h6 class="card-title">افزودن سانس جدید</h6>
                @if (ViewBag.Error != null)
                {
                    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
                }
            <form asp-controller="Reserve" asp-action="Create" method="post" >

                <div class="row col-12">
                    <div class="form-group col-12">

                        <div class="form-group col-md-12">
                            <label>هزینه سانس</label>
                            <input type="number" asp-for="Price" class="form-control" placeholder="هزینه سانس را وارد کنید">
                   
                        </div>
                    </div>
                    <div class="form-group col-6">
                        <label>ساعت شروع سانس:</label>
                        <div class="input-group clockpicker">
                            <input type="text" asp-for="StartTime" class="form-control" placeholder="ساعت شروع سانس">
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-time"></span>
                            </span>
                        </div>
                        <span class="text-danger" asp-validation-for="StartTime"></span>

                    </div>
                    <div class="form-group col-6">
                        <label>ساعت اتمام سانس:</label>
                        <div class="input-group clockpicker">
                            <input type="text" asp-for="EndTime" class="form-control " placeholder="ساعت اتمام سانس">
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-time"></span>
                            </span>
                        </div>
                        <span class="text-danger" asp-validation-for="EndTime"></span>
                        <input type="hidden" asp-for="CollectionId" value="@ViewBag.id" />
                    </div>
                </div>
                <div class=" row col-12">
                      
                    <div class="form-group col-6">
                        <label>انتخاب تاریخ شروع :</label>

                        <div class="input-group">
                            <div class="input-group-prepend">

                            </div>
                            <div class="flex-grow-1">
                                <input asp-for="StartDayTime" type="text" class="form-control w-100" DatePicker="1">
                            </div>
                        </div>       <span class="text-danger" asp-validation-for="StartDayTime"></span>
                    </div>
             
                    <div class="form-group col-6">
                        <label>انتخاب تاریخ  اتمام :</label>

                        <div class="input-group">
                            <div class="input-group-prepend">

                            </div>
                            <div class="flex-grow-1">
                                <input asp-for="EndDayTime" type="text" class="form-control w-100" DatePicker="1">
                            </div>
                        </div> <span class="text-danger" asp-validation-for="EndDayTime"></span>
                    </div>
                   
                </div>
                    <button type="submit" class="btn btn-primary submit">ثبت</button>
            </form>
            </div>
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Reserve/Edit.cshtml
@model EditReserveViewModel
@{
    ViewData["Title"] = "ویرایش سانس";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="row">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <div class="d-flex justify-content-end px-4">
                <a class="d-inline-block mt-3 text-black" href="/Admin/Reserve/@Model.CollectionId">
                    سانس ها
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left">
                        <line x1="19" y1="12" x2="5" y2="12"></line>
                        <polyline points="12 19 5 12 12 5"></polyline>
                    </svg>
                </a>
            </div>
            <div class="card-body pt-0">
                <h6 class="card-title">ویرایش سانس </h6>
                @if (ViewBag.Error != null)
                {
                    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
                }
                <form asp-controller="Reserve" asp-action="Edit" method="post">

                    <div class="row col-12">
                        <div class="form-group col-12">

                            <div class="form-group col-md-12">
                                <label>هزینه سانس</label>
                                <input type="number" asp-for="Price" class="form-control" placeholder="هزینه سانس را وارد کنید">

                            </div>
                        </div>
                        <div class="form-group col-6">
                            <label>ساعت شروع سانس:</label>
                            <div class="input-group clockpicker">
                                <input type="text" asp-for="StartTime" class="form-control" placeholder="ساعت شروع سانس">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-time"></span>
                                </span>
                            </div>
                            <span class="text-danger" asp-validation-for="StartTime"></span>

                        </div>
                        <div class="form-group col-6">
                            <label>ساعت اتمام سانس:</label>
                            <div class="input-group clockpicker">
                                <input type="text" asp-for="EndTime" class="form-control " placeholder="ساعت اتمام سانس">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-time"></span>
                                </span>
                            </div>
                            <span class="text-danger" asp-validation-for="EndTime"></span>
                            <input type="hidden" asp-for="CollectionId" />
                            <input type="hidden" asp-for="Id"  />
                        </div>
                    </div>
                    <div class=" row col-12">

                        <div class="form-group col-6">
                            <label>انتخاب تاریخ  :</label>

                            <div class="input-group">
                                <div class="input-group-prepend">

                                </div>
                                <div class="flex-grow-1">
                                    <input asp-for="DayTime" type="text" class="form-control w-100" DatePicker="1">
                                </div>
                            </div>       <span class="text-danger" asp-validation-for="DayTime"></span>
                        </div>

                      

                    </div>
                    <button type="submit" class="btn btn-primary submit">ثبت</button>
                </form>
            </div>
        </div>
    </div>
</div>

ReserveSport/Areas/Admin/Views/Reserve/Index.cshtml
@model Tuple<List<ReserveViewModel>, int, int>
@{
    ViewData["Title"] = "سانس ها";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h6 class="card-title">لیست سانس ها </h6>
                <div class="row justify-content-between">
                    <div class="col-md-6 mb-1 mb-md-0">
                        <a href="/Admin/Reserve/Create/@ViewBag.id" class="btn text-white btn-success">افزودن</a>
                    </div>
                   

                </div>
                <div class="table-responsive pt-3">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    ساعت شروع
                                </th>

                                <th>
                                  ساعت اتمام 
                                </th>
                                <th>
                                   تاریخ
                                </th>
                                <th>
                                   قیمت
                                </th>
                              

                                <th>
                                    عملیات
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Item1)
                            {
                                <tr id="item_@item.Id">

                                    <td>
                                        @item.StartTime
                                    </td>
                                    <td>
                                        @item.EndTime
                                    </td>
                                    <td>@item.DayTime</td>
                                    <td>@item.Price.ToString("0,#")</td>
                                  
                                    <td>
                                        <div class="dropdown mb-2">
                                            <button class="btn p-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal icon-lg text-muted pb-3px"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
                                            </button>
                                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                                <a class="dropdown-item d-flex align-items-center" href="/Admin/Reserve/Edit/@item.Id">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2 icon-sm ml-2"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg> <span class="">ویرایش</span>
                                                </a>
                                               

                                                <button onclick="DeleteReserve('@item.Id')" class="dropdown-item d-flex align-items-center"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash icon-sm ml-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg> <span class="">حذف</span></button>

                                            </div>

                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @if (Model.Item2 > 1)
                    {
                        <div class="dataTables_paginate paging_simple_numbers py-3 d-flex justify-content-center" id="dataTableExample_paginate">
                            <ul class="pagination">
                                <li class="paginate_button page-item previous @((Model.Item3-1 == 0) ? "disabled" : "")" id="dataTableExample_previous">
                                    <a 
                                       asp-controller="Reserve" asp-action="Index" asp-route-id="@ViewBag.id" asp-route-page="@(Model.Item3-1)" 
                                       
                                       aria-controls="dataTableExample" data-dt-idx="0" tabindex="0" class="page-link">قبلی</a>
                                </li>
                                @for (int i = 1; i <= (Model.Item2); i++)
                                {
                                    <li class="paginate_button page-item @(Model.Item3==i?"active":"")">
                                        <a 
                                            asp-controller="Reserve" asp-action="Index" asp-route-id="@ViewBag.id" asp-route-page="@i" 
                                           aria-controls="dataTableExample" data-dt-idx="1" tabindex="0" class="page-link">@i</a>
                                    </li>
                                }
                                <li class="paginate_button page-item @((Model.Item3+1 > Model.Item2) ? "disabled" : "")" id="dataTableExample_next">
                                    <a asp-controller="Reserve" asp-action="Index" asp-route-id="@ViewBag.id" asp-route-page="@(Model.Item3+1)"  aria-controls="dataTableExample" data-dt-idx="4" tabindex="0" class="page-link">بعدی</a>
                                </li>
                            </ul>
                        </div>
                    }
                </div>
              
              
            </div>
        </div>
    </div>
</div>